jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          install-yarn: true
          override-ci-command: yarn
      - run: yarn test
version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
